### ISSUE TITLE
Failed to activate the feedback package

### ISSUE THREAD

**Issue by techeverri** [atom/feedback#39]
steps to reproduce below:

1. Update packeges
2. That's it!

**Atom Version**: 0.188.0
**System**: Windows 8.1
**Thrown From**: [feedback](https://github.com/atom/feedback) package, v0.38.0

### Stack Trace

Failed to activate the feedback package

```
At Cannot read property 'length' of null

TypeError: Cannot read property 'length' of null
  at Object.module.exports.setReporter (C:\Users\techeverri\.atom\packages\feedback\lib\reporter.coffee:6:5)
  at Object.module.exports.consumeReporter (C:\Users\techeverri\.atom\packages\feedback\lib\feedback.coffee:32:14)
  at Provider.module.exports.Provider.provide (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\node_modules\service-hub\lib\provider.js:30:34)
  at ServiceHub.module.exports.ServiceHub.consume (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\node_modules\service-hub\lib\service-hub.js:48:18)
  at Package.module.exports.Package.activateServices (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:368:69)
  at Package.module.exports.Package.activateNow (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:243:16)
  at C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:221:30
  at Package.module.exports.Package.measure (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\src\package-manager.js:461:21)
  at C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\node_modules\settings-view\lib\package-manager.js:226:29
  at exit (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\src\buffered-process.js:63:47)
  at C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\src\buffered-process.js:70:18
  at Socket.<anonymous> (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\src\buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)
  at EventEmitter.ipc.sendSync (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as getSize] (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\atom.asar\renderer\api\lib\remote.js:110:29)
  at Atom.module.exports.Atom.getWindowDimensions (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\src\atom.js:520:29)
  at Atom.module.exports.Atom.storeDefaultWindowDimensions (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\src\atom.js:552:25)
  at C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\src\window-event-handler.js:105:21
  at handler (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\src\space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at elemData.handle (C:\Users\techeverri\AppData\Local\atom\app-0.188.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -1:18.6 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "save-session"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-snippets, v1.2.0
color-picker, v1.5.0
editor-stats, v0.17.0
editorconfig, v0.3.3
feedback, v0.38.0
file-icons, v1.5.2
linter, v0.12.0
linter-csslint, v0.0.11
linter-htmlhint, v0.0.10
linter-jshint, v0.1.0
revert-buffer, v0.5.0
Search, v0.4.0

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
First of all you shouldn't have install the `feedback` package directly. It's a core package and might rely on un-released features (although not the case this time). I recommend you uninstall it since it's already bundled with Atom.

Now, I'm pretty sure this is a duplicate, I just cannot find the main tracking issue. Regardless, this problem went away after you restarted Atom, right? If it did, then this is indeed a dupe, and the underlying problem is caused by package modules remaining in Node's module cache. If a package updates its API by changing a function name, when we try to activate the package after an update, we are still using the cached version of the module which causes issues with service initialization for instance. More details in the tracking issue (that I cannot find).

/cc @jlord @atom/non-github-maintainers
